[package]
name = "dns-adblock"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "^1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
] }
hickory-proto = "0.26.0"
hickory-resolver = { version = "0.26.1", features = ["tokio"] }
adblock = { version = "0.12.3" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.102"
reqwest = "0.13.3"
toml = "1.1.2"
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
fs-err = "3.3.0"
futures = "0.3.32"
sha2 = "0.11.0"
chrono = { version = "0.4.44", features = ["serde"] }
scopeguard = "1.2.0"
axum = { version = "0.8.9", features = ["ws"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "chrono"] }
serde_json = "1.0.149"
addr = "0.15.6"
rcgen = "0.14.7"
axum-server = { version = "0.8", features = ["tls-rustls"] }
tower-http = { version = "0.6.9", features = ["trace", "cors"] }
base64 = "0.22.1"
yansi = "1.0.1"
parking_lot = "0.12.5"
rustls = "0.23.40"
time = "0.3.47"
rustls-pemfile = "2.2.0"
tokio-rustls = "0.26.4"
regex = "1.12.3"
notify = "9.0.0-rc.4"
notify-debouncer-full = "0.8.0-rc.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_System_Rpc",
    "Win32_Security",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis"
] }
widestring = "1.2.1"

[build-dependencies]
winres = "0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
