[workspace]
members = ["vox", "crates/*", "clients/*"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
publish = false

[workspace.dependencies]
anyhow = "1.0.103"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
yansi = "1.0.1"
regex = "1.12.4"
serde = { version = "1.0.228", features = ["derive"] }
fs-err = "3.3.0"
toml = "1.1.2"
tokio = { version = "^1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "signal"
] }
hickory-proto = "0.26.1"
hickory-resolver = { version = "0.26.1", features = ["tokio", "https-ring", "rustls-platform-verifier", "dnssec-ring"] }
rand = "0.10.1"
futures = "0.3.32"
hickory-client = "0.25.2"
dashmap = "7.0.0-rc2"
moka = "0.12.15"
clap = { version = "4.6.1", features = ["derive"] }
windows-service = "0.8.0"
instant-acme = "0.8.5"
adblock = "0.13.0"
reqwest = { version = "0.13.4", features = ["zstd", "brotli", "gzip"] }
time = "0.3.53"

vox_shared = { path = "crates/vox_shared", version = "0.1.0" }
vox_dns = { path = "crates/vox_dns", version = "0.1.0" }
vox_lists = { path = "crates/vox_lists", version = "0.1.0" }
vox_windows = { path = "crates/vox_windows", version = "0.1.0" }

[profile.release]
debug = true
debug-assertions = false
overflow-checks = false
lto = "thin"
codegen-units = 16
incremental = false
panic = "abort"

[profile.max-perf]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
