[workspace]
members = ["vox", "crates/*"]
resolver = "3"

[workspace.dependencies]
vox_shared = { path = "crates/vox_shared", version = "0.1.0" }

[profile.release]
debug = true
debug-assertions = false
overflow-checks = false
lto = "thin"
codegen-units = 16
incremental = false
panic = "abort"

[profile.max-perf]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"