[package]
name = "vox_windows_client"
version = "0.1.0"
edition = "2024"

[dependencies]
vox_shared = { workspace = true }
windivert = "0.7.0-beta.4"
windivert-sys = "0.11.0-beta.2"
tracing = { workspace = true }
anyhow = { workspace = true }
fs-err = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true, rand = "0.9.4" }
hickory-client = { workspace = true }
vox_dns = { workspace = true }
clap = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-service = { workspace = true }
