[package]
name = "vox"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
hickory-proto = { workspace = true }
hickory-resolver = { workspace = true }
adblock = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
chrono = { version = "0.4.44", features = ["serde"] }
axum = { version = "0.8.9", features = ["ws", "macros"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "chrono"] }
serde_json = "1.0.149"
addr = "0.15.6"
axum-server = { version = "0.8", features = ["tls-rustls"] }
tower-http = { version = "0.7.0", features = ["trace", "cors"] }
base64 = "0.22.1"
yansi = { workspace = true }
parking_lot = "0.12.5"
rustls = "0.23.40"
time = "0.3.47"
rustls-pemfile = "2.2.0"
regex = { workspace = true }
notify = "9.0.0-rc.4"
notify-debouncer-full = "0.8.0-rc.2"
clap = { workspace = true }
include_dir = "0.7.4"
mime_guess2 = "2.0.5"
maxminddb = { version = "0.29.0", features = ["mmap"] }
rand = { workspace = true }
dashmap = { workspace = true }
argon2 = "0.6.0-rc.8"
cliclack = "0.5.4"
hex = "0.4.3"
vox_shared = { workspace = true }
vox_dns = { workspace = true }
vox_lists = { workspace = true }
which = { workspace = true }
instant-acme = { workspace = true }
x509-parser = "0.18.1"
vox_windows = { workspace = true }
arc-swap = "1.9.2"

[build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.dependencies]
windows-service = { workspace = true }

[dev-dependencies]
rcgen = { version = "0.14.8", default-features = false, features = ["aws_lc_rs"] }

[[bin]]
name = "cli"
path = "src/cli/main.rs"

[[bin]]
name = "daemon"
path = "src/main.rs"
