[package]
name = "vox_lists"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
adblock = { workspace = true }
anyhow = { workspace = true }
bitflags = "2.11.1"
chrono = { version = "0.4.44", features = ["serde"] }
fs-err = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
sha2 = "0.11.0"
toml = { workspace = true }
tracing = { workspace = true }
vox_shared = { workspace = true }
dashmap = { workspace = true }