[package]
name = "vox_dns"
version = "0.1.0"
edition = "2024"

[dependencies]
hickory-proto = { workspace = true }
hickory-resolver = { workspace = true }
hickory-client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
moka = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
vox_shared = { workspace = true }
rand = { workspace = true }
